# Generated by Django 4.2.4 on 2024-05-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_irpf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='documents',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_irpf.customer')),
            ],
        ),
    ]
