# Generated by Django 4.2.4 on 2024-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irpf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(max_length=110),
        ),
    ]
