# Generated by Django 4.2.4 on 2024-04-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_irpf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
