# Generated by Django 4.2.4 on 2024-05-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_irpf', '0002_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='documents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(max_length=110, null=True),
        ),
    ]
